### PR TITLE
Edit comments

### PR DESCRIPTION
**Pull request by blancadesal**
Creating this PR to discuss the comments by @geohci in utils.py

```python
# Maybe it's too much of an edge case to worry about, but technically if "),(" appeared in a data tuple -- 
# e.g., as part of a #page title -- it would be split falsely. I wonder if there is some lightweight way 
# to enforce the # of expected columns and intelligently recombine broken tuples?
    
records = re.split(r'\),\(', values[1:-1])  # Strip `(` and `)`
return parse_records(records)
```

Good question. I remember this was a major issue when I first wrote the code doing the microtask. There are indeed parentheses (and not always balanced) within the Wikipedia page titles, but the `parse_records()` function (which is a wrapper around `csv.reader`) expects all rows to have the same # of fields, so if one or some of the tuples are broken, it would throw an error - I've tested the function on some of the larger files containing page titles and it has never crashed so far.

The question then is why this line works:
```python
records = re.split(r'\),\(', values[1:-1])  # Strip `(` and `)`
```
I think the reason is that the regex splits on ),( and that when "," appears in a page title, it's followed by a `_` to denote a blank space. I haven't tested on all possible files so maybe this wouldn't work in all types of fields. I have no better idea right now, suggestions are more than welcome.

Regarding mapping SQL dtypes to Python dtypes, I think that's a good idea. E.g. I know Pandas does a very good job of inferring dtypes when reading from a CSV, but the same can not be said for all other ways of creating a dataframe, such as from a Python dict.

### CODE REVIEW

**Comment by geohci** [comment]
Regarding the regex: Yeah, the edge case titles probably aren't going to arise in the main namespace of English Wikipedia because of the reason you raise. I did a quick search and found a number in Wikimedia Commons such as: https://commons.wikimedia.org/w/index.php?title=File:Venn_Diagram_of_sets_((P),(Q),(R)).jpg
That file name would show up in: https://dumps.wikimedia.org/commonswiki/latest/commonswiki-latest-page.sql.gz
If you want a smaller file to test, it looks like there's an example in German Wikiversity too (https://de.wikiversity.org/wiki/Fl%C3%A4chenberechnung/(0,1),(2,0),(1,3)/Erzeugtes_Polygon/Aufgabe), so: https://dumps.wikimedia.org/dewikiversity/latest/dewikiversity-latest-page.sql.gz

There's a related question which is how to handle exceptions in the parsing. My inclination is to use the [approach of the CSV library](https://docs.python.org/3/library/csv.html#csv-fmt-params), which is parameterized (so at least can choose between no errors allowed and yielding the broken rows) but I'm open to suggestions.

Regarding SQL types: I'll leave it up to you how feasible you think it is. If we don't include it, that's perfectly fine with me. If we do include it, just make sure that it is also a parameter that the user can change (so you can just receive the fields as strings too in case it throws errors or corrupts the data somehow).

**Comment by blancadesal** [comment]
> Regarding the regex: Yeah, the edge case titles probably aren't going to arise in the main namespace of English Wikipedia because of the reason you raise. I did a quick search and found a number in Wikimedia Commons such as: https://commons.wikimedia.org/w/index.php?title=File:Venn_Diagram_of_sets_((P),(Q),(R)).jpg

So I've run some tests with these titles and what happens is not quite what I expected! When the string is parsed into a list by the ),( splitting regex, it does indeed split up the title names. This is the bad news.

The (kind of) good news is that `csv.reader()` then manages to cobble the row back together again, but I have no idea *how* this works. Like, if magic exists, this is it... The ),( are of course stripped away, so the title comes out wrong, i.e. 

Venn_Diagram_of_sets_((P),(Q),(R)).jpg ->
Venn_Diagram_of_sets_((PQR)).jpg

Whether the tuple with the 'tricky' title name is in the beginning, end, middle, or is the only tuple in an INSERT INTO statement doesn't matter, `csv.reader()` handles this like a champ. So based on this (to me) baffling behavior, what if we keep the ),( instead of stripping them away? Surprisingly, this also works: `csv.reader()` still knows which element in the list of strings belongs to which row - the only unwanted effect is that we're now also keeping the ),( that act as actual tuple separators so we need to filter them out when yielding from the generator.

This is not a very elegant solution but seems to work for now.

**Comment by blancadesal** [comment]
> There's a related question which is how to handle exceptions in the parsing. My inclination is to use the approach of the CSV library, which is parameterized (so at least can choose between no errors allowed and yielding the broken rows) but I'm open to suggestions.

Do you mean the `strict` parameter?

> `Dialect.strict`
When `True`, raise exception `Error` on bad CSV input. The default is `False`.

If so, I've been using `strict=True` as the default behavior, but the choice could ofc be left to the user.

**Comment by geohci** [comment]
> So based on this (to me) baffling behavior, what if we keep the ),( instead of stripping them away? Surprisingly, this also works: csv.reader() still knows which element in the list of strings belongs to which row - the only unwanted effect is that we're now also keeping the ),( that act as actual tuple separators so we need to filter them out when yielding from the generator.

That sounds great to me -- good exploration and thinking for using the CSV library to begin with! This is why I use tabs as delimiters for everything I do though :) I'm sure there are other weird edge-cases having to do with `/` and quotes etc. that we aren't thinking of but CSV would handle too.

> If so, I've been using strict=True as the default behavior, but the choice could ofc be left to the user.

Yep, that's reasonable. Just make sure that the user can change that setting to False if desired when they instantiate the mwsql object.

**Comment by blancadesal** [comment]
Sooo, I've rebuilt the SQL parser from the ground up, no longer using the CSV library. After a deep dive into `pyparsing` and CFG, and a very bad time with increasingly more cryptic regexes from hell, I ended up implementing the parser from scratch using Python's `csv.reader` C code as inspiration. The code still needs refactoring, exception-handling, etc. but it already runs faster than my first version: 1.5 min vs. 2.5 min for 1M rows from `enwiki page`, and (I think) handles all the edge cases.

In other news, I've managed to make a mess of my own git branches, working by myself, so I'll spend some time on cleanup now :))

**Comment by geohci** [comment]
> Sooo, I've rebuilt the SQL parser from the ground up, no longer using the CSV library. After a deep dive into pyparsing and CFG, and a very bad time with increasingly more cryptic regexes from hell, I ended up implementing the parser from scratch using Python's csv.reader C code as inspiration. 

Taking a step back -- can you help me understand what wasn't working with the CSV library?

**Comment by blancadesal** [comment]
> Taking a step back -- can you help me understand what wasn't working with the CSV library?

The problem was not with the CSV library but in the step just before - I couldn't find a way to split between tuples without also splitting up tuples inside strings (the edge cases we looked at). So I rewrote the split function to keep track of state, i.e. if the parsers current position is inside a quoted string, inside a tuple, etc. - but then I realized that this is basically what the CSV reader does in the first place. So instead of feeding the output of the new split function to the CSV reader, I just modified it a tiny bit to do all the parsing in one pass. Does this make sense?

**Comment by blancadesal** [comment]
Update. I refactored and streamlined the code, added optional dtype conversion, made changes according to your suggestions, etc. and life was seemingly very good until I started testing on `enwiki pages`. Turns out there are more edge cases:  (2R,3S,4S)-3,4,5,7,3',4'-hexahydroxyflavan and similar fail because of the `'` character followed by a `,`.

This is because I haven't found a good way of dealing with escaped `'` yet, turns out you can't just test for the presence of an escaped char in a string as if it were another character, i.e. if your escape char is `\`, then 

```python
if current_char == "'" and previous_char == '\\':
    do something
````
will not detect that the `'` in `I'm` isn't the end of a quoted string in this example:

 `'Hi, I\'m an escaped quote char!'`

Not sure where to go from here right now. Thought about going back to `csv.reader` because of it's "magic" ability to stitch up broken tuples (albeit imperfectly); however, when testing on larger input I discovered that the magic doesn't always work either - the main difference being that I don't know why it works when it does, while I know exactly why my home-grown parser fails. 😭

**Comment by geohci** [comment]
Ok, I think I understand now why you wanted to depart from the CSV library. Based on the other edge cases, I currently lean towards going back to CSV because it's simpler. We can build a full version of the library w/ the caveat that weird titles can lead to unexpected behavior and then come back to it. Could you also create a quick PAWS notebook with a few example edge cases so I can play with it too?

**Comment by blancadesal** [comment]
> Ok, I think I understand now why you wanted to depart from the CSV library. Based on the other edge cases, I currently lean towards going back to CSV because it's simpler. We can build a full version of the library w/ the caveat that weird titles can lead to unexpected behavior and then come back to it. Could you also create a quick PAWS notebook with a few example edge cases so I can play with it too?

https://public.paws.wmcloud.org/User:Slst2020/SQL_parser.ipynb

Put this together a bit in a rush... let me know if something is unclear.

**Comment by geohci** [comment]
Thanks! Yeah, I played around a little and didn't see a perfect solution when using CSV or custom parsers/regexes. My suggestion would be one of two things:
* Try ast.literal_eval again -- it didn't work for all the examples you had in the notebook but it wasn't clear to me if those are the syntax that would be used in the dumps
* Stick with CSV and just file an issue that notes this weird parsing of edge-case strings with the `),(` sequence in them. It seems to happen rarely enough that it's okay to not have a solution for.

**Comment by blancadesal** [comment]
> Thanks! Yeah, I played around a little and didn't see a perfect solution when using CSV or custom parsers/regexes. My suggestion would be one of two things:
> 
> * Try ast.literal_eval again -- it didn't work for all the examples you had in the notebook but it wasn't clear to me if those are the syntax that would be used in the dumps
> * Stick with CSV and just file an issue that notes this weird parsing of edge-case strings with the `),(` sequence in them. It seems to happen rarely enough that it's okay to not have a solution for.

Option two sounds good to me - `ast.literal_eval` did a good job with the actual parsing but is ~10 times slower. For the larger files, this means going from 15-20 min to over 3 hours in some cases.

I've reverted back to the csv reader approach and am currently testing on different files across different wikis. You can see the results in this PAWS notebook:
https://public.paws.wmcloud.org/User:Slst2020/Parsing_test_log.ipynb

The tests only check whether the output contains the expected number of fields, so the case with the tuples in the page_titles getting some of their parentheses stripped isn't covered. So far, I've not run across any cases of fields having been merged - the problem is strings being split in two, or sometimes more, fragments.

Another problem I've run across is the encoding in svwiki categorylinks. Here's an example tuple from the raw SQL file:
> (6246,'Artiklar_med_successionsbox_som_bör_uppdateras','BZL0*@*@T**@T*BZL0*@ܿ�����	','2020-09-08 13:21:29','Myrdal, Alva','uca-sv-u-kn','page')

Do you have any idea what could be going on?

As you mentioned, the dump files are supposed to be utf-8 - it's even stated in the dump file metadata. I had a problem with another file earlier but it worked when I switched to Latin-1 (ISO-8859). It was caused by the Ñ character, although I haven't been able to extract the tuple/string that contained it.

**Comment by blancadesal** [comment]
Restructured utils.py to contain only non-parser related functions and added a utility function to handle file opening to remove redundancy from the code.

Also removed the "code playground" notebook as it's more convenient to use PAWS for this.

**Comment by blancadesal** [comment]
Moved parser functions from utils.py into their own parser.py module.

**Comment by geohci** [comment]
Sticking with CSV works for me!

Thanks for making that PAWS notebook. A few thoughts:
* Based on the Commons examples, it looks like the NULL replacement you do should actually look for `'NULL'` to reduce the likelihood of it matching the word `NULL` in titles.
* What is going on with the externallinks examples?

Regarding svwiki categorylinks, I checked and looked like not just svwiki. I can file a bug report on Phabricator and subscribe you so you can chime is as needed / you'd like if that sounds good to you. I suspect it's an issue with the dumps and not us.

**Comment by blancadesal** [comment]
> * Based on the Commons examples, it looks like the NULL replacement you do should actually look for `'NULL'` to reduce the likelihood of it matching the word `NULL` in titles.

Good catch! I'm replacing `NULL` with `'NULL'` now instead of stripping it away. The user can decide what to do with null values later when cleaning the data. This also avoids confusion with true empty strings.
 
> * What is going on with the externallinks examples?

Not quite sure why they're being split up like that, will get back to you after exploring further.

> Regarding svwiki categorylinks, I checked and looked like not just svwiki. I can file a bug report on Phabricator and subscribe you so you can chime is as needed / you'd like if that sounds good to you. I suspect it's an issue with the dumps and not us.

Sounds good to me!

The code is ready for another code review :)) I've made quite substantial changes though, including renaming files and moving functions around, so I'm not sure if the best way is to go through the diffs in this PR... What would you suggest?

I've created a PAWS notebook to play around with too:
https://public.paws.wmcloud.org/User:Slst2020/mwsql_playground.ipynb

**Comment by blancadesal** [comment]
Most suggested changes have been implemented – see comments in code for details.

**Pull request merged**
